#pragma once

#define VIAL_KEYBOARD_UID {0xFB, 0xDD, 0xF4, 0xD2, 0xCF, 0xB4, 0x70, 0x8B}
#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 13 }
#define RGB_MATRIX_DEFAULT_HUE 128
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 130
#define VIALRGB_NO_DIRECT